//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vohmencev_KFC_App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderContent
    {
        public string Dish { get; set; }
        public int Paycheck { get; set; }
        public string DishStatus { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Status Status { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
