//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vohmencev_KFC_App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public string StaffLogin { get; set; }
        public string StaffPassword { get; set; }
        public string FullName { get; set; }
        public string Position { get; set; }
    
        public virtual Positions Positions { get; set; }
    }
}
